### ISSUE TITLE
Some CSS issues

### ISSUE THREAD

**Issue by sbillard** [JimBrown/zenfluid#19]
The "gear" icon has a box around it which is not the usual rendering.

The "themeswitcher menu" overwrites the word main. 

See attached

![2018-03-03 11_55_01-main _ home link](https://user-images.githubusercontent.com/2474007/36938705-6436ced6-1eda-11e8-9082-69137d736889.png)

**Comment by JimBrown** [comment]
I put the box around the gear icon because with the the fluid design, it's possible the picture being displayed will fill the screen and if the top left of the picture is dark the gear could get lost.

![image](https://user-images.githubusercontent.com/6067232/36946581-eb7518b4-1f8c-11e8-8d19-7ec2d67d1db5.png)

**Comment by JimBrown** [comment]
Regarding the themeswitcher menu. Will have to think about that one. I forgot about that plugin as I never used it.

**Comment by JimBrown** [comment]
I'm thinking I might just move both those items into the menus as regular menu items that display only if user has appropriate rights.

**Comment by sbillard** [comment]
Sounds good to me. The general intent is to make these as little intrusive as possible on the theme pages.

**Comment by JimBrown** [comment]
Having had a look at the code, it will require some major rewriting of both of these to do that. Instead, I'm going to see if I can move the theme switcher icon over near the admin toolbox icon. (But only in my theme. Will leave defaults alone.)

I've also been squashing some bugs in the theme options, as well as setting some saner option defaults. One thing I did notice, if an option default is set to "false", the database ends up with a "NULL" instead of "0" for that option after running setup (with theme options purged first). This causes some issues. If the option is set to "true", the database has a "1" for that option. If the theme options are then updated in the admin backend, the unticked options then get the "0" value in the database. Perhaps a bug in setup? Everything works fine if I specify "1" or "0" instead of "true" or "false" for the option defaults in themeoptions.

**Comment by sbillard** [comment]
That should be possible. There are a couple of filters to allow themes to intervene with these icons. But maybe also it could simply be done with CSS (e.g. right justify?)

**Comment by JimBrown** [comment]
CSS is the direction I'm heading... ;-)

**Comment by JimBrown** [comment]
ThemeSwitcher support has been added.
